server:
  port: 3060

spring:
  application:
    name: mall-tiny
  profiles:
    active: dev
  #  main:
  #    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: UNIX_TIMESTAMP() # 逻辑已删除值(默认为 当前时间戳 秒)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /api/v1/admin/login
      - /api/v1/admin/register
      - /api/v1/admin/info
      - /api/v1/admin/logout

# cos相关配置
tencentyun:
  cos:
    endpoint: cos.ap-shanghai.myqcloud.com # cos对外服务的访问域名
    region: ap-shanghai # 地域
    secretId: AKID3sSmpb7MK0TfZCYeT1LPCjzzh8IBn8Cy # 访问身份验证中用到用户标识
    secretKey: XooXzA4h27vSiiRt4zd06wVnnX0C6j6B # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: jinpika-1308276765 # oss的存储空间
    dir:
      prefix: bootdemo-file/ # 上传文件夹路径前缀